# Generated by Django 3.1.2 on 2020-11-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_task_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_status',
            field=models.CharField(default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='task_urgency',
            field=models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High')], default='L', max_length=1),
        ),
    ]
