# Generated by Django 3.1.2 on 2020-11-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201102_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('d1', 'Development'), ('d2', 'Researcher'), ('d3', 'Administrative')], default='Select', max_length=10),
        ),
    ]
