# Generated by Django 3.1.2 on 2020-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='Task_Done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('s', 'Select'), ('d1', 'Development'), ('d2', 'Researcher'), ('d3', 'Administrative')], default='s', max_length=10),
        ),
    ]
