# Generated by Django 3.1.2 on 2020-11-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20201102_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Task_Done',
            new_name='task_completed',
        ),
    ]
