# Generated by Django 3.1.2 on 2020-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20201102_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.CharField(choices=[('s', 'Select'), ('d1', 'Development'), ('d2', 'Researcher'), ('d3', 'Administrative')], default='s', max_length=10),
        ),
    ]
