# Generated by Django 3.1.2 on 2020-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.CharField(choices=[('s', 'Choose'), ('A', 'A'), ('d2', 'B'), ('d3', 'C')], default='s', max_length=10),
        ),
    ]
