# Generated by Django 3.1.2 on 2020-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20201102_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
