# Generated by Django 3.1.2 on 2020-11-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20201102_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_description',
        ),
    ]
