# Generated by Django 3.1.2 on 2020-11-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employee_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_descriptions',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
