# Generated by Django 3.1.2 on 2020-11-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20201102_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='task_descriptions',
            new_name='task_description',
        ),
    ]
