# Generated by Django 3.1.2 on 2020-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_remove_employee_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_details',
            field=models.TextField(default='Not Defined'),
        ),
    ]
