# Generated by Django 3.1.2 on 2020-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_employee_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task_details',
            field=models.TextField(default='Not Defined', null=True),
        ),
    ]
