# Generated by Django 3.1.2 on 2020-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20201102_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_details',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_num2',
            field=models.CharField(default=2, max_length=13),
            preserve_default=False,
        ),
    ]
