# Generated by Django 2.1.15 on 2020-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_auto_20201110_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.CharField(choices=[('s', 'Choose'), ('A', 'A'), ('d2', 'B'), ('d3', 'C')], default='s', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_details',
            field=models.TextField(default='Not Defined', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='task_urgency',
            field=models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
