# Generated by Django 2.1.15 on 2020-11-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_auto_20201110_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_details',
            field=models.TextField(default='Add task Details', null=True),
        ),
    ]
